apps/urls.py
from django.urls import path, re_path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('student/list/', views.list_student, name='list_student'),
    path('student/create/', views.StudentCreate.as_view(), name='create_student'),
    re_path(r'^student/edit/(?P<pk>\d+)/$', views.StudentEdit.as_view(), name='edit_student'),
    re_path(r'^student/delete/(?P<pk>\d+)/$', views.StudentDelete.as_view(), name='delete_student'),

    path('register/user/', views.RegisterUser.as_view(), name='register_user'),
    path('book/list/', views.BooksList.as_view(), name='book_list'),
    path('book/create/', views.BooksCreate.as_view(), name='book_create'),
    re_path(r'^book/view/(?P<pk>\d+)/$', views.BooksDetail.as_view(), name='book_view'),
    re_path(r'^book/delete/(?P<pk>\d+)/$', views.BooksDelete.as_view(), name='book_delete'),
]

uno/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.contrib.auth.views import login, logout_then_login

from apps import views

urlpatterns = [
    path('', views.index, name='home'),
    path('admin/', admin.site.urls),
    path('home/', include('apps.urls')),
    re_path('^login/$', login, {'template_name': 'user/login/index.html'}, name='login'),
    path('logout/', logout_then_login, name='logout'),
]

apps/models.py
import datetime

from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils import timezone


class Register(models.Model):
    name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=70)
    email = models.EmailField()
    password = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Subject(models.Model):
    name = models.CharField(max_length=50)
    number_credits = models.IntegerField()

    def __str__(self):
        return u'{}'.format(self.name)


class Student(models.Model):
    name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    subject_student = models.ManyToManyField(Subject)

    def full_name(self):
        return u'{} {}'.format(self.name, self.last_name)


class Books(models.Model):
    title = models.CharField(max_length=150, )
    sub_title = models.CharField(max_length=100, )
    author = models.CharField(max_length=100, )
    description = models.TextField(max_length=800, )
    content = models.TextField(max_length=2000, )
    date_created = models.DateField(("Date"), default=datetime.date.today)

    def __str__(self):
        return u'{}'.format(self.title)

apps/forms.py
from django import forms
from django.contrib.auth.models import User

from apps.models import Student, Books, Register


# User Register
class RegisterForm(forms.ModelForm):
    class Meta:
        model = Register
        fields = '__all__'

        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'password': forms.PasswordInput(attrs={'class': 'form-control'})
        }


class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = '__all__'

        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'subject_student': forms.SelectMultiple(attrs={'class': 'form-control'})
        }


class BooksForm(forms.ModelForm):
    class Meta:
        model = Books
        fields = '__all__'

        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'sub_title': forms.TextInput(attrs={'class': 'form-control'}),
            'author': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control'}, ),
            'content': forms.Textarea(attrs={'class': 'form-control'}),
            'date_created': forms.DateInput(attrs={'class': 'form-control'}),
        }

apps/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.generic import CreateView, UpdateView, DeleteView, ListView, DetailView, FormView

from apps.models import Student, Books, Register
from apps.forms import StudentForm, BooksForm, RegisterForm


# Create your views here.

@login_required
def index(request):
    return render(request, template_name='index.html')


def list_student(request):
    student = Student.objects.all()
    return render(request, template_name='list_student.html', context={'student': student})


class RegisterUser(FormView):
    model = Register
    form_class = RegisterForm
    template_name = 'user/login/register.html'


class StudentCreate(CreateView):
    model = Student
    form_class = StudentForm
    template_name = 'add_student.html'

    def get_success_url(self):
        return reverse('list_student')


class StudentEdit(UpdateView):
    model = Student
    form_class = StudentForm
    template_name = 'edit_student.html'

    def get_success_url(self):
        return reverse('list_student')


class StudentDelete(DeleteView):
    model = Student
    form_class = StudentForm
    template_name = 'delete_student.html'

    def get_context_data(self, **kwargs):
        context_data = super(StudentDelete, self).get_context_data(**kwargs)
        pk = self.kwargs.get('pk')
        student = Student.objects.get(id=int(pk))
        context_data.update({'student': student})
        return context_data

    def get_success_url(self):
        return reverse('list_student')


class BooksList(ListView):
    model = Books
    template_name = 'books/books.html'


class BooksDetail(DetailView):
    model = Books
    template_name = 'books/books_view.html'


class BooksDelete(DeleteView):
    model = Books
    form_class = BooksForm
    template_name = 'books/books_delete.html'

    def get_context_data(self, **kwargs):
        context_data = super(BooksDelete, self).get_context_data(**kwargs)
        pk = self.kwargs.get('pk')
        book = Student.objects.get(id=int(pk))
        context_data.update({'book': book})
        return context_data

    def get_success_url(self):
        return reverse('book_list')


class BooksCreate(CreateView):
    model = Books
    form_class = BooksForm
    template_name = 'books/books_add.html'

    def get_success_url(self):
        return reverse('book_list')

templates/add_student.html
{% extends 'layouts/base.html' %}

{% load staticfiles %}


{% block stylesheet %} {% endblock %}

{% block content %}
    <h1>Add Students</h1>

    <form method="post" class="form-horizontal">
        {% csrf_token %}
        {% for hidden in form.hidden_fields %}
            {{ hidden }}
        {% endfor %}
        <div class="form-group">
            <label for="{{ form.name.id_for_label }}" class="col-sm-2 control-label">{{ form.name.label }}</label>
            <div class="col-sm-8">
                {{ form.name }}
            </div>
        </div>

        <div class="form-group">
            <label for="{{ form.last_name.id_for_label }}"
                   class="col-sm-2 control-label">{{ form.last_name.label }}</label>
            <div class="col-sm-8">
                {{ form.last_name }}
            </div>
        </div>

        <div class="form-group">
            <label for="{{ form.subject_student.id_for_label }}"
                   class="col-sm-2 control-label">{{ form.subject_student.label }}</label>
            <div class="col-sm-8">
                {{ form.subject_student }}
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-8">
                <input class="btn btn-success pull-right" type="submit" name="submit" value="Save">
                <a class="btn btn-secondary" href="{% url 'list_student' %}">Back</a>
            </div>

        </div>
    </form>
{% endblock %}

{% block javascripts %} {% endblock %}

templates/books/books.html
{% extends 'layouts/base.html' %}

{% load staticfiles %}

{% block stylesheet %} {% endblock %}

{% block content %}
    <table class="table table-bordered">
        <thead>
        <tr>
            <th>Book</th>
            <th>Author</th>
            <th>Created</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        {% for bk in books_list %}
            <tr>
                <td>{{ bk.title }}</td>
                <td>{{ bk.author }}</td>
                <td>{{ bk.date_created }}</td>
                <td>
                    <a class="btn btn-warning" style="color: white;" href="{% url 'book_view' bk.id %}">View</a>
                    <a class="btn btn-danger" style="color: white;" href="{% url 'book_delete' bk.id %}">Delete</a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <a class="btn btn-info" href="{% url 'book_create' %}">Create Books</a>
{% endblock %}

{% block javascripts %} {% endblock %}

templates/books/books_add.html
{% extends 'layouts/base.html' %}

{% load staticfiles %}


{% block stylesheet %} {% endblock %}

{% block content %}
    <form method="post" class="form-horizontal">
        {% csrf_token %}
        {% for hidden in form.hidden_fields %}
            {{ hidden }}
        {% endfor %}
        <div class="form-group">
            <label for="{{ form.title.id_for_label }}" class="col-sm-2 control-label">{{ form.title.label }}</label>
            <div class="col-sm-8">
                {{ form.title }}
            </div>
        </div>

        <div class="form-group">
            <label for="{{ form.sub_title.id_for_label }}"
                   class="col-sm-2 control-label">{{ form.sub_title.label }}</label>
            <div class="col-sm-8">
                {{ form.sub_title }}
            </div>
        </div>

        <div class="form-group">
            <label for="{{ form.author.id_for_label }}" class="col-sm-2 control-label">{{ form.author.label }}</label>
            <div class="col-sm-8">
                {{ form.author }}
            </div>
        </div>

        <div class="form-group">
            <label for="{{ form.description.id_for_label }}"
                   class="col-sm-2 control-label">{{ form.description.label }}</label>
            <div class="col-sm-8">
                {{ form.description }}
            </div>
        </div>

        <div class="form-group">
            <label for="{{ form.content.id_for_label }}" class="col-sm-2 control-label">{{ form.content.label }}</label>
            <div class="col-sm-8">
                {{ form.content }}
            </div>
        </div>

        <div class="form-group">
            <label for="{{ form.date_created.id_for_label }}"
                   class="col-sm-2 control-label">{{ form.date_created.label }}</label>
            <div class="col-sm-8">
                {{ form.date_created }}
            </div>
        </div>

        <div class="form-group">
            <label for="{{ form.user_created.id_for_label }}"
                   class="col-sm-2 control-label">{{ form.user_created.label }}</label>
            <div class="col-sm-8">
                {{ form.user_created }}
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-8">
                <input class="btn btn-success pull-right" type="submit" name="submit" value="Save">
                <a class="btn btn-secondary" href="{% url 'book_list' %}">Back</a>
            </div>

        </div>
    </form>
{% endblock %}

{% block javascripts %} {% endblock %}

templates/books/books_delete.html
{% extends 'layouts/base.html' %}

{% load staticfiles %}

{% block stylesheet %} {% endblock %}

{% block content %}
    <h1 style="text-align: center; color: #bd2130;"></h1>
    <img src="{% static 'Img/Delete_Icon.png' %}" alt="Delete" class="rounded mx-auto d-block" style="width: 15%;">

    <form method="post">
        {% csrf_token %}
        <p class="text-danger">sure you want to delete the <strong>{{ books.title }}</strong> book published by user <strong>{{ books.user_created }}</strong></p>
        <div class="col-sm-offset-2 col-sm-8">
            <input class="btn btn-danger" type="submit" name="submit" value="Delete">
            <a class="btn btn-info" href="{% url 'book_list' %}">No</a>
        </div>
    </form>
{% endblock %}

{% block javascripts %} {% endblock %}

templates/books/books_view.html
{% extends 'layouts/base.html' %}

{% load staticfiles %}

{% block stylesheet %} {% endblock %}

{% block content %}
    <h1>{{ books.title }}</h1>
    <h2>{{ books.sub_title }}</h2>
    <p>{{ books.description }}</p>
    <p>{{ books.content }}</p>
    <p><strong>{{ books.author }}</strong></p>
    <p>{{ books.date_created }}</p>
    <p>{{ books.user_created }}</p>
    <a class="btn btn-primary mr-auto" href="{% url 'book_list' %}">Back</a>
{% endblock %}

{% block javascripts %} {% endblock %}

templates/delete_student.html
{% extends 'layouts/base.html' %}

{% load staticfiles %}


{% block stylesheet %} {% endblock %}

{% block content %}
    <h1 style="text-align: center; color: #bd2130;"></h1>
    <img src="{% static 'Img/Delete_Icon.png' %}" alt="Delete" class="rounded mx-auto d-block" style="width: 15%;">

    <form method="post">
        {% csrf_token %}
        <p class="text-danger">You are sure you want to eliminate the student {{ student.full_name }}</p>
        <div class="col-sm-offset-2 col-sm-8">
            <input class="btn btn-danger" type="submit" name="submit" value="Delete">
            <a class="btn btn-info" href="{% url 'list_student' %}">No</a>
        </div>
    </form>
{% endblock %}

{% block javascripts %} {% endblock %}

templates/edit_student.html
{% extends 'layouts/base.html' %}

{% load staticfiles %}


{% block stylesheet %} {% endblock %}

{% block content %}
    <h1>Edit Student</h1>

    <form method="post" class="form-horizontal">
        {% csrf_token %}
        {% for hidden in form.hidden_fields %}
            {{ hidden }}
        {% endfor %}
        <div class="form-group">
            <label for="{{ form.name.id_for_label }}" class="col-sm-2 control-label">{{ form.name.label }}</label>
            <div class="col-sm-8">
                {{ form.name }}
            </div>
        </div>

        <div class="form-group">
            <label for="{{ form.last_name.id_for_label }}"
                   class="col-sm-2 control-label">{{ form.last_name.label }}</label>
            <div class="col-sm-8">
                {{ form.last_name }}
            </div>
        </div>

        <div class="form-group">
            <label for="{{ form.subject_student.id_for_label }}"
                   class="col-sm-2 control-label">{{ form.subject_student.label }}</label>
            <div class="col-sm-8">
                {{ form.subject_student }}
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-8">
                <input class="btn btn-success pull-right" type="submit" name="submit" value="Save">
                <a class="btn btn-secondary" href="{% url 'list_student' %}">Back</a>
            </div>
        </div>
    </form>
{% endblock %}

{% block javascripts %} {% endblock %}

templates/index.html
{% extends 'layouts/base.html' %}

{% load staticfiles %}


{% block stylesheet %} {% endblock %}

{% block content %}
    <!-- Begin page content -->
    <main role="main" class="container">
        <h1 class="mt-5">Home</h1>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolorem error eveniet nulla obcaecati quas quia
            sit? Commodi cumque explicabo hic odit quaerat quis! Assumenda at aut cupiditate dicta dignissimos ducimus
            facere impedit ipsa laboriosam, odit perferendis, reiciendis rerum sed sunt suscipit temporibus, ullam unde.
            xAb architecto beatae deserunt dolorum ex explicabo hic, ipsam, itaque laudantium minima molestiae mollitia
            necessitatibus nihil non odio odit optio quia quibusdam rem saepe sed sequi sit, tempora ullam ut vel
            voluptate! Aut consequatur fugiat harum iste molestiae nemo obcaecati reiciendis sint veniam. Amet aperiam,
            architecto consequuntur dicta doloremque ea eaque eius et facilis harum labore maxime molestiae nemo nisi
            non sequi soluta vitae. Dolor doloremque enim, et laboriosam nostrum sequi voluptatum. Animi atque deserunt
            eius esse est expedita facere fugit harum illum impedit ipsa laudantium libero molestiae molestias nihil
            pariatur perspiciatis, quae quam quibusdam quis quisquam quod repellat repellendus, sed tempore temporibus
            ut voluptas voluptatem.</p>
    </main>
{% endblock %}

{% block javascripts %} {% endblock %}

templates/layouts/base.html
{% load  staticfiles %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'libs/boostrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static "css/footer.css" %}">
    {% block stylesheet %} {% endblock %}
    <title>Index</title>
</head>
<body>

{% block nav %}
    {% include 'layouts/navbar.html' %}
{% endblock %}

<div class="container mb-3 mt-3 pb-4">
    {% block content %}{% endblock %}
</div>

{% block footer %}
<footer class="footer mb-auto">
    <div class="container">
        <span class="text-muted">Place sticky footer content here.</span>
    </div>
</footer>
{% endblock %}

<script src="{% static 'libs/boostrap/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'libs/boostrap/popper.min.js' %}"></script>
<script src="{% static 'libs/boostrap/js/bootstrap.min.js' %}"></script>
{% block javascripts %}{% endblock %}
</body>
</html>

templates/layouts/navbar.html
<header>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top" style="background-color: #4C756E; color: white;">
        <a class="navbar-brand" href="#">BOOKS</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02"
                aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
            {% if request.user.is_authenticated %}
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item ">
                        <a class="nav-link" href="{% url 'index' %}">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item ">
                        <a class="nav-link" href="{% url 'list_student' %}">List</a>
                    </li>
                    <li class="nav-item ">
                        <a class="nav-link" href="{% url 'book_list' %}">Books</a>
                    </li>
                    <li class="nav-item dropdown ">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink"
                           data-toggle="dropdown"
                           aria-haspopup="true" aria-expanded="false">
                            Gallery
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" href="#">Django</a>
                            <a class="dropdown-item" href="#">Python</a>
                            <a class="dropdown-item" href="#">Javascript</a>
                            <a class="dropdown-item" href="#">Html</a>
                            <a class="dropdown-item" href="#">Css</a>
                            <a class="dropdown-item" href="#">MySql</a>
                            <a class="dropdown-item" href="#">Terminal</a>
                        </div>
                    </li>
                </ul>
                <form class="form-inline mt-2 mt-md-0" style="margin-right: 10px;">
                    <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-warning my-2 my-sm-0" type="submit">Search</button>
                </form>
                <ul class="navbar-nav">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink"
                           data-toggle="dropdown"
                           aria-haspopup="true" aria-expanded="false">
                            {{ request.user }}
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink" style="left: -60px;">
                            <a class="dropdown-item" href="#">My Profile</a>
                            <a class="dropdown-item" href="#">Settings</a>
                            <button class="btn btn-info" type="submit" style="margin-left: 20px;">
                                <a href="/logout" style="text-decoration: none; color: white;">Logout</a></button>
                        </div>
                    </li>
                </ul>
            {% else %}
                <form method="post" class="form-inline mt-2 mt-md-0 ml-auto ">
                    <div class="col-md-12">
                        {% csrf_token %}
                    </div>
                    <div class="form-group">
                        <input type="text" name="username" class="form-control mr-sm-2" placeholder="Username">
                    </div>
                    <div class="form-group">
                        <input type="password" name="password" class="form-control mr-sm-2" placeholder="Password">
                    </div>

                    <div class="form-group">
                        <input type="submit" name="login" class="btn btn-info form-control mr-sm-2" value="Start">
                    </div>
                        <a href="{% url 'register_user' %}" style="text-decoration: none; color: #fff;">Register</a>
                </form>
            {% endif %}
        </div>
    </nav>
</header>

templates/list_student.html
{% extends 'layouts/base.html' %}

{% load staticfiles %}


{% block stylesheet %} {% endblock %}

{% block content %}
    <h1 style="text-align: center; color: #bd2130;">Student List</h1>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th>Name</th>
            <th>Last Name</th>
            <th>Profesion</th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>
        </thead>
        <tbody>
        {% for stu in student %}
            <tr>
                <td>{{ stu.name }}</td>
                <td>{{ stu.last_name }}</td>
                <td>
                    {% for sb_s in stu.subject_student.all %}
                        {{ sb_s.name }} <br/>
                    {% endfor %}
                </td>
                <td><a class="btn btn-warning" style="color: white;" href="{% url 'edit_student' stu.id %}">Edit</a>
                </td>
                <td><a class="btn btn-danger" style="color: white;" href="{% url 'delete_student' stu.id %}">Delete</a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <a class="btn btn-info" href="{% url 'create_student' %}">New Student</a>
{% endblock %}

{% block javascripts %} {% endblock %}

templates/user/login/index.html
{% extends 'layouts/base.html' %}

{% load staticfiles %}


{% block stylesheet %} {% endblock %}


{% block content %}
    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img class="d-block w-100" src="{% static 'img/logouno.jpg' %}"
                     alt="First slide" style="height: 500px;">
            </div>
            <div class="carousel-item">
                <img class="d-block w-100" src="{% static 'img/logodos.jpg' %}"
                     alt="Second slide" style="height: 500px;">
            </div>
            <div class="carousel-item">
                <img class="d-block w-100" src="{% static 'img/logotres.jpg' %}"
                     alt="Third slide" style="height: 500px;">
            </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
    <div class="card-deck mt-4">
        <div class="card">
            <img class="card-img-top" src="{% static 'img/python.png' %}" alt="Card image cap">
            <div class="card-body">
                <h5 class="card-title">Card title</h5>
                <p class="card-text">This is a wider card with supporting text below as a natural lead-in to
                    additional content. This content is a little bit longer.</p>
            </div>
            <div class="card-footer">
                <small class="text-muted">Last updated 3 mins ago</small>
            </div>
        </div>
        <div class="card">
            <img class="card-img-top" src="{% static 'img/python.png' %}" alt="Card image cap">
            <div class="card-body">
                <h5 class="card-title">Card title</h5>
                <p class="card-text">This card has supporting text below as a natural lead-in to additional
                    content.</p>
            </div>
            <div class="card-footer">
                <small class="text-muted">Last updated 3 mins ago</small>
            </div>
        </div>
        <div class="card">
            <img class="card-img-top" src="{% static 'img/python.png' %}" alt="Card image cap">
            <div class="card-body">
                <h5 class="card-title">Card title</h5>
                <p class="card-text">This is a wider card with supporting text below as a natural lead-in to
                    additional content. This card has even longer content than the first to show that equal height
                    action.</p>
            </div>
            <div class="card-footer">
                <small class="text-muted">Last updated 3 mins ago</small>
            </div>
        </div>
    </div>
{% endblock %}

{% block javascripts %} {% endblock %}

templates/user/login/register.html
{% extends 'layouts/base.html' %}

{% load staticfiles %}


{% block stylesheet %} {% endblock %}

{% block nav %}
        <nav class="navbar position-fixed">
            <form class="form" >
                <button class="btn btn-warning" type="submit">
                    <a href="{% url 'home' %}" style="color: #fff; text-decoration: none;">Back</a>
                </button>
            </form>
        </nav>
{% endblock %}

{% block content %}
    <!-- At Work-->
    <body style="background: black">
    <h1 style="text-align: center; color: white;">At Work!</h1>
    <div class="text-center mb-4">
            <img class="mb-4" src="{% static 'img/panda.png' %}" alt="" width="272" height="272">
        </div>
    </body>
    <!----------->


 <!--   <form class="form-signin w-25" method="post" style="margin: auto;">
    {#% csrf_token %#}
        <div class="text-center mb-4">
            <img class="mb-4" src="{#% static 'img/panda.png' %#}" alt="" width="72" height="72">
            <h1 class="h3 mb-3 font-weight-normal">Register</h1>
            <p></p>
        </div>

    {#% for field in form %#}
      <p>
        {#  #}{ field.label_tag }}<br>
        {#  #}{ field }}
        {#% if field.help_text %#}
          <small style="color: grey">{#  #}{ field.help_text }}</small>
        {#% endif %#}
        {#% for error in field.errors %#}
          <p style="color: red">{#  #}{ error }}</p>
        {#% endfor %#}
      </p>
    {#% endfor %#}*/

        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
    </form>-->
{% endblock %}

{% block footer %} {% endblock %}
{% block javascripts %} {% endblock %}